FROM python

RUN mkdir /work
RUN pip install pip --upgrade
RUN pip install ansible

RUN apt-get update -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    sshpass vim git

COPY script.sh /work
COPY ansible_files/* /work
WORKDIR /work
