apiVersion: v1
kind: ConfigMap
metadata:
  name: gpu-config
data:
  config.json: |
    {
      "docker" : "18.03.1-ce"
    }
# kubectl create configmap gpu-config --from-file ./golang/configs/config.json
