apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-deploy
  labels:
    app: ansible-app
  annotations:
spec:
  selector:
    matchLabels:
      app: ansible-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ansible-app
    spec:
      containers:
      - name: ansible-app
        image: rahulroshank/ansible:1.2
        imagePullPolicy: Always
        command: 
          - /bin/sh 
          - /work/script.sh
