apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-deploy
  labels:
    app: ansible-app
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  selector:
    matchLabels:
      app: ansible-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: ansible-app
    spec:
      volumes:
      - name: gpu-config-vol
        configMap:
            name: gpu-config
      containers:
      - name: ansible-app
        image: rahulroshank/ansible:1.2
        imagePullPolicy: Always
        volumeMounts:
            - name: gpu-config-vol
              mountPath: /tmp
        envFrom:
            - configMapRef:
                name: gpu-config
