---
- hosts: all
  become_user: rahul
  tasks:
  - name: Add the public key to authorized keys to compute hosts
    authorized_key:
        user: rahul
        state: present
        key: '{{ item }}'
        with_file:
            -  ~/.ssh/id_rsa.pub
  - name: Copy upgrade script file
    copy:
      src: /work/upgrade.sh
      dest: /home/rahul
      mode: '0777'
  - name: Copy config file
    copy:
      src: /tmp/config.json
      dest: /home/rahul
      mode: '0777'
  - name: Execute file
    shell: /home/rahul/upgrade.sh 2>&1 | tee /home/rahul/log.txt
