---
- hosts: all
  become_user: rahul
  tasks:
  - name: Copy file
    copy:
      src: /work/upgrade.sh
      dest: /home/rahul
      mode: '0777'
  - name: Execute file
    shell: /home/rahul/upgrade.sh > /home/rahul/log.txt
