apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gpu
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rahulroshan-kachchap/TS-Lighthouse-ArgoCD.git
    targetRevision: HEAD
    path: gpu
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ansible-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
